## Data preparation

In [1]:
import os
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
from netCDF4 import num2date, Dataset
import xarray as xr
from tools import CreateGridBox_subextent, save_hdf, IntersectShapefiles
import rasterio
import xarray as xr

### First checking the administrative boundaries
Here we add admin level-1 FNID to the admin level-2 shapefile.

In [2]:
# Load FEWSNET admin boundaries of Somalia (1990)
adm1_1990 = gpd.read_file('./data/shapefile/SO_Admin1_1990.shp')   # Total 18 FNID
adm2_1990 = gpd.read_file('./data/shapefile/SO_Admin2_1990.shp')   # Total 74 FNID
# - Insert admin_1 FNID to the admin_2 shapefile
adm1_1990 = adm1_1990.rename({'FNID':'FNID_ADM1'}, axis=1)
adm2_1990 = adm2_1990.merge(adm1_1990[['FNID_ADM1','ADMIN1']], on='ADMIN1')
adm2_1990 = adm2_1990[np.roll(adm2_1990.columns, 1)]
adm2_1990.to_file('./data/shapefile/SO_admin2_1990_revised.shp')
# Get sub_extent from shapefile
sub_bound = adm2_1990.total_bounds   # [left, bottom, right, top] 
sub_extent = sub_bound[[0,2,1,3]]    # [minx,maxx,miny,maxy]

### 1) CHIRPS Precipitation
CHIRPS data: /home/ftp_out/products/CHIRPS-2.0/global_monthly/netcdf/

We create a graticule of the CHIRPS-Africa for the extent of the country, then we intersect it with admin level-2 shapefile and calculate an area of each segment (grid or partial grid).

In [3]:
# Get the extent of CHIRPS data
with rasterio.open('./data/chirps-v2.0.2020.01.01.tif') as src:
    affine = src.meta['transform']
    dx, dy = affine.a, -affine.e
    bounds = np.array(src.bounds)   # [left, bottom, right, top] 
    extent = bounds[[0,2,1,3]]      # [minx,maxx,miny,maxy]

# (1) Create a graticule of CHIRPS data
filn_out = './data/shapefile/SO_admin2_chirps.shp'
CreateGridBox_subextent(filn_out, extent, dx, dy, sub_extent, set_print=False)
    
# (2) Intersection of CHIRPS with admin level-2 boundaries
ref = './data/shapefile/SO_admin2_chirps.shp'
adm = './data/shapefile/SO_admin2_1990_revised.shp'
IntersectShapefiles(ref, adm, outSHP=ref, set_print=False)

# (3) Calculate the areas of the intersected polygons
# Reproject to Somalia UTM: UTM zone 38N (EPSG:20538)
filn_out = './data/shapefile/SO_admin2_chirps.shp'
grid_dist = gpd.read_file('./data/shapefile/SO_admin2_chirps.shp')
grid_dist = grid_dist.to_crs(epsg=20538)    # UTM zone 18S
# Caculate areas of all split polygons
grid_dist["area_km2"] = grid_dist['geometry'].area / 10**6
# Save GeoDataFrame to Shapefile
grid_dist.to_file(filn_out)
print('%s is saved.' % filn_out)

./data/shapefile/SO_admin2_chirps.shp is saved.

In [4]:
# Load CHIPRS data
temp = np.load('/Users/dlee/data/chirps/africa_monthly_198101_202008.npz', allow_pickle=True)
prcp = temp['data']
ntim, nlat, nlon = prcp.shape
lat, lon, tim = temp['lat'], temp['lon'], temp['tim']
tim = [str(period) for period in tim]
tim = pd.to_datetime(tim, format='%Y-%m')
tim = tim.to_period('M')
prcp = prcp.reshape([ntim,nlat*nlon])

# Spatial averages in administrative units
grid = gpd.read_file('./data/shapefile/SO_admin2_chirps.shp')
listID = np.sort(grid.FNID.unique())
nID = len(listID)
prcp_dist = pd.DataFrame(np.zeros([ntim,nID]), index=tim, columns=listID)
prcp_dist.index.name = 'time'
for fnid in listID:
    subID = grid[grid.FNID == fnid].ID.astype(int)
    subData = prcp[:, subID.values]
    subData[np.isnan(subData)] = 0    # Assume 0 values at NaN grids
    subArea = grid[grid.FNID == fnid].area_km2
    # Area-averaged data
    prcp_dist[fnid] = (subData @ subArea)/subArea.sum()
save_hdf('./data/SO_admin2_chirps.hdf',prcp_dist)
del prcp, lat, lon, tim
prcp_dist.head()

./data/SO_admin2_chirps.hdf is saved.

,SO1990A21101,SO1990A21102,SO1990A21103,SO1990A21104,SO1990A21201,SO1990A21202,SO1990A21203,SO1990A21301,SO1990A21302,SO1990A21303,...,SO1990A22604,SO1990A22605,SO1990A22606,SO1990A22701,SO1990A22702,SO1990A22703,SO1990A22801,SO1990A22802,SO1990A22803,SO1990A22804
time,,,,,,,,,,,,,,,,,,,,,
1981-01,2.912159,3.393857,3.959673,4.684031,1.688224,3.054894,1.573421,1.683044,0.886342,1.970712,...,0.935361,0.666849,0.587090,0.503367,0.520322,0.666045,0.908092,1.167884,1.697125,0.460263
1981-02,6.108098,3.403615,3.825072,5.734320,3.422284,0.816510,4.052085,2.131610,1.645105,3.141231,...,3.449212,2.025924,1.225686,1.895644,1.436128,2.996263,2.233642,4.323137,3.012077,1.668710
1981-03,98.124783,37.571041,24.489698,38.142071,69.228262,5.022367,80.427226,19.767632,12.826464,56.478382,...,175.486449,80.770001,83.535444,56.259073,23.186481,88.210897,67.812608,87.942516,90.648058,21.433080
1981-04,54.722570,41.421288,17.285735,13.692762,54.295913,54.075556,60.011767,48.734963,46.363409,42.619214,...,178.953473,159.615907,237.558113,260.007454,212.241230,243.490429,128.639451,222.602866,124.473864,148.601705
1981-05,20.387662,15.846781,5.546454,5.490030,29.849543,36.360596,28.079327,34.120321,25.020623,33.296629,...,57.342453,49.820345,50.529063,140.364868,200.955812,84.728848,195.259813,118.377835,162.798667,195.209250

### 2) Evaporative Demand
Reference ET (ET0) Monitoring Data set (uses MERRA-2 atmospheric reanalysis)

In [5]:
# Get the extent of ETos data
filn_etos = './data/ETos_fine_1981-2020.nc'
nc = Dataset(filn_etos, 'r')
lat = -np.array(nc.variables['lat']); dy = 0.125
lon = np.array(nc.variables['lon']); dx = 0.125
extent = [lon[0]-dx/2, lon[-1]+dx/2, lat[-1]-dy/2, lat[0]+dy/2]   # [minx, maxx, miny, maxy]

# (1) Create a graticule of ETos data
filn_out = './data/shapefile/SO_admin2_etos.shp'
CreateGridBox_subextent(filn_out, extent, dx, dy, sub_extent, set_print=False)
    
# (2) Intersection of ETos with admin level-2 boundaries
ref = './data/shapefile/SO_admin2_etos.shp'
adm = './data/shapefile/SO_admin2_1990_revised.shp'
IntersectShapefiles(ref, adm, outSHP=ref, set_print=False)

# (3) Calculate the areas of the intersected polygons
# Reproject to Somalia UTM: UTM zone 38N (EPSG:20538)
filn_out = './data/shapefile/SO_admin2_etos.shp'
grid_dist = gpd.read_file('./data/shapefile/SO_admin2_etos.shp')
grid_dist = grid_dist.to_crs(epsg=20538)    # UTM zone 18S
# Caculate areas of all split polygons
grid_dist["area_km2"] = grid_dist['geometry'].area / 10**6
# Save GeoDataFrame to Shapefile
grid_dist.to_file(filn_out)
print('%s is saved.' % filn_out)

./data/shapefile/SO_admin2_etos.shp is saved.

In [6]:
# Load ETos data
etos = np.array(nc.variables['ETos'])
etos = etos[:,::-1,:]         # NetCDF data is flipped
ntim, nlat, nlon = etos.shape
tim = nc.variables['time']
tim = num2date(tim[:], tim.units, tim.calendar)
tim = ['%04d-%02d' % (t.year, t.month) for t in tim]
tim = pd.to_datetime(tim, format='%Y-%m')
tim = tim.to_period('M')
etos = etos.reshape([ntim,nlat*nlon])

# Spatial averages in administrative units
grid = gpd.read_file('./data/shapefile/SO_admin2_etos.shp')
listID = np.sort(grid.FNID.unique())
nID = len(listID)
etos_dist = pd.DataFrame(np.zeros([ntim,nID]), index=tim, columns=listID)
etos_dist.index.name = 'time'
for fnid in listID:
    subID = grid[grid.FNID == fnid].ID.astype(int)
    subData = etos[:, subID.values]
    subData[np.isnan(subData)] = 0    # Assume 0 values at NaN grids
    subArea = grid[grid.FNID == fnid].area_km2
    # Area-averaged data
    etos_dist[fnid] = (subData @ subArea)/subArea.sum()
save_hdf('./data/SO_admin2_etos.hdf',etos_dist)
del etos, lat, lon, tim
etos_dist.head()

./data/SO_admin2_etos.hdf is saved.

,SO1990A21101,SO1990A21102,SO1990A21103,SO1990A21104,SO1990A21201,SO1990A21202,SO1990A21203,SO1990A21301,SO1990A21302,SO1990A21303,...,SO1990A22604,SO1990A22605,SO1990A22606,SO1990A22701,SO1990A22702,SO1990A22703,SO1990A22801,SO1990A22802,SO1990A22803,SO1990A22804
time,,,,,,,,,,,,,,,,,,,,,
1981-01,154.923766,149.890819,147.676142,149.988299,155.946775,147.701981,148.496767,166.864062,183.012041,160.385631,...,240.831983,247.965481,262.089501,241.907174,217.081127,251.925101,217.196124,242.588044,211.674128,196.797090
1981-02,149.086542,146.640680,145.980852,147.509156,154.260121,144.120182,145.008143,168.984857,184.765616,161.667371,...,234.585529,239.024149,254.453304,230.711113,204.164114,245.359792,208.272786,233.984943,204.291552,185.790154
1981-03,163.432622,167.723676,164.569557,160.849498,178.966591,176.497229,167.745362,196.170205,217.614981,186.874226,...,220.484666,232.589830,242.134478,197.066908,178.655696,213.846653,184.914221,201.938172,178.938363,167.221511
1981-04,151.783335,169.146789,171.252679,162.524911,162.089230,169.865413,155.987737,172.017217,189.706183,162.591478,...,166.252215,174.682481,177.505661,158.677297,155.762867,164.897558,164.841615,161.143939,160.753003,153.156825
1981-05,182.973390,201.739250,207.001174,198.187711,184.236077,198.790717,181.353521,187.486778,204.948976,178.312332,...,163.038574,172.373040,161.944940,136.989380,131.240546,154.183190,152.282607,151.472816,148.397358,134.974777

### 3) FLDAS
[Famine Early Warning Systems Network (FEWS NET) Land Data Assimilation System](https://ldas.gsfc.nasa.gov/fldas) </br>
FLDAS data can be downloaded from here: https://hydro1.gesdisc.eosdis.nasa.gov/data/FLDAS/

### 4) MODIS

MODIS data download from here: https://modis.gsfc.nasa.gov/data/dataprod/mod13.php

### 5) AFRICA Cropmask (IIASA-IFPRI Crop fraction area)

In [6]:
filn = './data/AFRICA_cropmask_IIASA-IFPRI_Crop_fraction_area_CHIRPS_0.05.nc'
nc = Dataset(filn, 'r')
crop_area = np.array(nc.variables['crop_area'])
lat = np.array(nc.variables['latitude'])
lon = np.array(nc.variables['longitude'])

In [15]:
crop_area[0]

array([-9.e+33,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00])

In [75]:
lat

array([-39.975, -39.925, -39.875, ...,  39.875,  39.925,  39.975],
      dtype=float32)

In [7]:
crop_area.shape

(1600, 1500)